# Import modules

In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV 

import warnings
warnings.filterwarnings('ignore')

In [4]:
"""
====Network Bandwidth========
1	0-5 GBps
2	5- 20 GBps
3	20 -50GBps
4	above  50 GBps
	
====User Type====
1	1-100
2	101-1000
3	1-1000
4	Above 1000

====Processor Speed (Per processor)====
1	1GHz-2GHz 
2	2GHz -4GHz
3	Above 4Hz
3	1GHz-4GHz 
	
====Ram====
1	16-32GB
2	32-64GB
3	Above 64GB
4	16-64GB
	
====vCPUs====
1	2 to 12
2	12 to 20
3	20  to 32
4	12 to 32

====OutPut====
1	St1.Nano
2	Mt2.GP
3	Lt3.Large
4	Lt4.Xlarge
5	Mt5.Prem

"""


'\n====Network Bandwidth========\n1\t0-5 GBps\n2\t5- 20 GBps\n3\t20 -50GBps\n4\tabove  50 GBps\n\t\n====User Type====\n1\t1-100\n2\t101-1000\n3\t1-1000\n4\tAbove 1000\n\n====Processor Speed (Per processor)====\n1\t1GHz-2GHz \n2\t2GHz -4GHz\n3\tAbove 4Hz\n\t\n====Ram====\n1\t16-32GB\n2\t32-64GB\n3\tAbove 64GB\n\t\n====vCPUs====\n1\t2 to 12\n2\t12 to 20\n3\t20  to 32\n\n====OutPut====\n1\tSt1.Nano\n2\tMt2.GP\n3\tLt3.Large\n4\tLt4.Xlarge\n\n'

# Loading the dataset

In [5]:
df = pd.read_csv('Data.csv')
df.head()

NetworkBandwidth  UserType  ProcessorSpeed  RAM  vCPUs  Output
0                 1         1               1    1      1       1
1                 3         2               2    2      2       2
2                 4         3               2    3      3       3
3                 4         4               3    3      3       4
4                 1         2               1    1      1       1

In [6]:
# to display stats about data
df.describe()

NetworkBandwidth   UserType  ProcessorSpeed        RAM      vCPUs  \
count         40.000000  40.000000       40.000000  40.000000  40.000000   
mean           2.800000   2.500000        2.125000   2.050000   2.150000   
std            1.304823   1.132277        0.757442   0.875595   0.863802   
min            1.000000   1.000000        1.000000   1.000000   1.000000   
25%            1.000000   1.750000        2.000000   1.000000   1.000000   
50%            3.000000   2.500000        2.000000   2.000000   2.000000   
75%            4.000000   3.250000        3.000000   3.000000   3.000000   
max            4.000000   4.000000        3.000000   3.000000   3.000000   

          Output  
count  40.000000  
mean    2.500000  
std     1.132277  
min     1.000000  
25%     1.750000  
50%     2.500000  
75%     3.250000  
max     4.000000

In [7]:
# to basic info about datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   NetworkBandwidth  40 non-null     int64
 1   UserType          40 non-null     int64
 2   ProcessorSpeed    40 non-null     int64
 3   RAM               40 non-null     int64
 4   vCPUs             40 non-null     int64
 5   Output            40 non-null     int64
dtypes: int64(6)
memory usage: 2.0 KB


In [8]:
# to display no. of samples on each class
# 'WickedChocolate','CoconutIsland','NutsPeanutButter','HeavenlyHazelnut','Chocolate','BerryBlonde'
df['Output'].value_counts()

4    10
3    10
2    10
1    10
Name: Output, dtype: int64

# Preprocessing the dataset

In [9]:
# check for null values
df.isnull().sum()

NetworkBandwidth    0
UserType            0
ProcessorSpeed      0
RAM                 0
vCPUs               0
Output              0
dtype: int64

# Label Encoder

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df['Output'] = le.fit_transform(df['Output'])
df.sample(2)
# df.head()

NetworkBandwidth  UserType  ProcessorSpeed  RAM  vCPUs  Output
34                 4         3               3    1      3       2
38                 4         3               2    1      1       2

# Model Training

In [24]:
from sklearn.model_selection import train_test_split
# train - 70
# test - 30
X = df.drop(columns=['Output'])
Y = df['Output']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.30)

In [40]:
import numpy

In [41]:
data_inputs = df[['NetworkBandwidth','UserType','ProcessorSpeed','RAM','vCPUs']].to_numpy()
data_outputs = df[['Output']].to_numpy()

In [42]:
print(data_inputs)

[[1 1 1 1 1]
 [3 2 2 2 2]
 [4 3 2 3 3]
 [4 4 3 3 3]
 [1 2 1 1 1]
 [3 3 2 2 2]
 [4 4 2 3 3]
 [4 1 3 3 3]
 [1 1 2 1 1]
 [3 2 3 2 2]
 [4 3 3 3 3]
 [4 4 1 3 3]
 [1 1 1 2 1]
 [3 2 2 3 2]
 [4 3 2 1 3]
 [4 4 3 1 3]
 [1 1 1 1 2]
 [3 2 2 2 3]
 [4 3 2 3 1]
 [4 4 3 3 1]
 [2 1 1 1 1]
 [4 2 2 2 2]
 [1 3 2 3 3]
 [1 4 3 3 3]
 [2 2 1 1 1]
 [4 3 2 2 2]
 [1 4 2 3 3]
 [1 1 3 3 3]
 [1 1 2 2 1]
 [3 2 3 3 2]
 [4 3 3 1 3]
 [4 4 1 1 3]
 [1 1 2 2 1]
 [3 2 3 3 2]
 [4 3 3 1 3]
 [4 4 3 1 3]
 [1 1 1 2 2]
 [3 2 2 3 3]
 [4 3 2 1 1]
 [4 4 3 1 1]]


In [43]:
print(data_output)

[[0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]]


In [29]:
data_outputs = numpy.array([[0.1],
                            [0.6],
                            [1.3],
                            [2.5]])

In [31]:
print(data_outputs)

[[0.1]
 [0.6]
 [1.3]
 [2.5]]


In [13]:
from sklearn.tree import DecisionTreeClassifier
# model = LogisticRegression()
# model = LinearDiscriminantAnalysis()
model = KNeighborsClassifier()
# model = DecisionTreeClassifier()
# model = GaussianNB()
# model = SVC()
# model = GradientBoostingClassifier(n_estimators=20, learning_rate=0.5, max_features=2, max_depth=2, random_state=0)

# model training
model.fit(x_train, y_train)

KNeighborsClassifier()

In [14]:
print("Accuracy: ",model.score(x_test, y_test) * 100)

Accuracy:  58.333333333333336


In [38]:
def predict_mpg(config, model):
    
    if type(config) == dict:
        df = pd.DataFrame(config)
    else:
        df = config
    
#     print(prepared_df)
    y_pred = model.predict(df)
    return y_pred
    

In [44]:
config = {
    'NetworkBandwidth': [1],
    'UserType': [1],
    'ProcessorSpeed': [1],
    'RAM': [1],
    'vCPUs': [1]
}

predictValue = predict_mpg(config, model)

OutPutList=["St1.Nano","Mt2.GP","Lt3.Large","Lt4.Xlarge"]

OutPutList[int(predictValue)]

'St1.Nano'

# Create Model File

In [30]:
import pickle

# Save to file in the current working directory
pkl_filename = "model.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(model, file)

# Load from file
with open(pkl_filename, 'rb') as file:
    pickle_model = pickle.load(file)
    
# Calculate the accuracy score and predict target values
score = pickle_model.score(x_test, y_test)
print("Test score: {0:.2f} %".format(100 * score))
Ypredict = pickle_model.predict(x_test)

Test score: 50.00 %


In [31]:
##loading the model from the saved file
pkl_filename = "model.pkl"
with open(pkl_filename, 'rb') as f_in:
    model = pickle.load(f_in)

predict_mpg(config, model)

array([0], dtype=int64)